# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-27 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fraud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('cardnumber', models.IntegerField(default=0)),
                ('mm', models.IntegerField(default=0)),
                ('yy', models.IntegerField(default=0)),
                ('cvv', models.IntegerField(default=0)),
                ('amount1', models.IntegerField(default=0)),
            ],
        ),
    ]
